// <auto-generated />
using System;
using FacturacionVERIFACTU.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FacturacionVERIFACTU.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FacturacionVERIFACTU.API.Models.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_postal");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Municipio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("municipio");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nif");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provincia");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Nif")
                        .IsUnique();

                    b.ToTable("empresas");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Models.Factura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("base_imponible");

                    b.Property<string>("ClienteNif")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cliente_nif");

                    b.Property<string>("ClienteNombre")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cliente_nombre");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CuotaIva")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("cuota_iva");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("EstadoVerifactu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado_verifactu");

                    b.Property<DateTime?>("FechaEnvioVerifactu")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_envio_verifactu");

                    b.Property<DateTime>("FechaExpedicion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_expedicion");

                    b.Property<DateTime?>("FechaOperacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_operacion");

                    b.Property<string>("HashVerifactu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hash_verifactu");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_factura");

                    b.Property<string>("QrCode")
                        .HasColumnType("text")
                        .HasColumnName("qr_code");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("serie");

                    b.Property<decimal>("TipoIva")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tipo_iva");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EstadoVerifactu");

                    b.HasIndex("FechaExpedicion");

                    b.HasIndex("EmpresaId", "Serie", "NumeroFactura")
                        .IsUnique();

                    b.ToTable("facturas");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Models.LineaFactura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("factura_id");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("importe");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("TipoIva")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tipo_iva");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("lineas_factura");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Models.Factura", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Models.Empresa", "Empresa")
                        .WithMany("Facturas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Models.LineaFactura", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Models.Factura", "Factura")
                        .WithMany("Lineas")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Models.Empresa", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Models.Factura", b =>
                {
                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
