// <auto-generated />
using System;
using FacturacionVERIFACTU.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FacturacionVERIFACTU.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Data.Entities.Albaran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_imponible");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("DireccionEntrega")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion_entrega");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<int?>("FacturaId")
                        .HasColumnType("integer")
                        .HasColumnName("factura_id");

                    b.Property<bool>("Facturado")
                        .HasColumnType("boolean")
                        .HasColumnName("facturado");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_entrega");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<int?>("PresupuestoId")
                        .HasColumnType("integer")
                        .HasColumnName("presupuesto_id");

                    b.Property<int>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("TotalIVA")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_iva");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FacturaId");

                    b.HasIndex("PresupuestoId");

                    b.HasIndex("SerieId");

                    b.HasIndex("TenantId", "Numero")
                        .IsUnique();

                    b.ToTable("albaranes");
                });

            modelBuilder.Entity("API.Data.Entities.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_imponible");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<bool>("EnviadaVERIFACTU")
                        .HasColumnType("boolean")
                        .HasColumnName("enviada_verifactu");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<DateTime?>("FechaEnvioVERIFACTU")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_envio_verifactu");

                    b.Property<string>("Huella")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("huella");

                    b.Property<string>("HuellaAnterior")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("huella_anterior");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<int>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("TotalIVA")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_iva");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("SerieId");

                    b.HasIndex("TenantId", "Numero")
                        .IsUnique();

                    b.ToTable("facturas");
                });

            modelBuilder.Entity("API.Data.Entities.LineaAlbaran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbaranId")
                        .HasColumnType("integer")
                        .HasColumnName("albaran_id");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("IVA")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("iva");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.HasKey("Id");

                    b.HasIndex("AlbaranId");

                    b.HasIndex("ProductoId");

                    b.ToTable("lineas_albaran");
                });

            modelBuilder.Entity("API.Data.Entities.LineaFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<int>("FacturaId")
                        .HasColumnType("integer")
                        .HasColumnName("factura_id");

                    b.Property<decimal>("IVA")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("iva");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("lineas_factura");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.CierreEjercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EnviadoVERIFACTU")
                        .HasColumnType("boolean")
                        .HasColumnName("enviado_verifactu");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_envio");

                    b.Property<string>("HashFinal")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_final");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TotalFacturas")
                        .HasColumnType("integer")
                        .HasColumnName("total_facturas");

                    b.Property<decimal>("TotalImporte")
                        .HasColumnType("decimal(28,2)")
                        .HasColumnName("total_importe");

                    b.Property<int>("ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("cierres_ejercicios");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ciudad");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nif");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Provincia")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provincia");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NIF")
                        .IsUnique();

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.LineaPrespuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("IVA")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("iva");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("PresupuestoId")
                        .HasColumnType("integer")
                        .HasColumnName("presupuesto_id");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.HasKey("Id");

                    b.HasIndex("PresupuestoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("lineas_presupuesto");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Presupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_imponible");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaValidez")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_validez");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<int>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.Property<int?>("SerieNumeracionId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(28,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("TotalIva")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_iva");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("SerieNumeracionId");

                    b.HasIndex("TenantId", "Numero")
                        .IsUnique();

                    b.ToTable("presupuestos");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<decimal>("IVA")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("iva");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidad");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Codigo")
                        .IsUnique();

                    b.ToTable("productos");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.SerieNumeracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("formato");

                    b.Property<int>("ProximoNumero")
                        .HasColumnType("integer")
                        .HasColumnName("proximo_numero");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Codigo", "Ejercicio")
                        .IsUnique();

                    b.ToTable("series_facturacion");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ciudad");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nif");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Provincia")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provincia");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("NIF")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreaccion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creaccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("API.Data.Entities.Albaran", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Cliente", "Cliente")
                        .WithMany("Albaranes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Data.Entities.Factura", "Factura")
                        .WithMany("Albaranes")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Presupuesto", "Presupuesto")
                        .WithMany("Albaranes")
                        .HasForeignKey("PresupuestoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.SerieNumeracion", "Serie")
                        .WithMany("Albaranes")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Factura");

                    b.Navigation("Presupuesto");

                    b.Navigation("Serie");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("API.Data.Entities.Factura", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.SerieNumeracion", "Serie")
                        .WithMany("Facturas")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Serie");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("API.Data.Entities.LineaAlbaran", b =>
                {
                    b.HasOne("API.Data.Entities.Albaran", "Albaran")
                        .WithMany("Lineas")
                        .HasForeignKey("AlbaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Producto", "Producto")
                        .WithMany("LineasAlbaran")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Albaran");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("API.Data.Entities.LineaFactura", b =>
                {
                    b.HasOne("API.Data.Entities.Factura", "Factura")
                        .WithMany("Lineas")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Producto", "Producto")
                        .WithMany("LineasFactura")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.CierreEjercicio", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Cliente", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Tenant", "Tenant")
                        .WithMany("Clientes")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.LineaPrespuesto", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Presupuesto", "Presupuesto")
                        .WithMany("Lineas")
                        .HasForeignKey("PresupuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Producto", "Producto")
                        .WithMany("LineasPresupuesto")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Presupuesto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Presupuesto", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Cliente", "Cliente")
                        .WithMany("Presupuestos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.SerieNumeracion", null)
                        .WithMany("Presupuestos")
                        .HasForeignKey("SerieNumeracionId");

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Producto", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Tenant", "Tenant")
                        .WithMany("Productos")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.SerieNumeracion", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Tenant", "Tenant")
                        .WithMany("Series")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Usuario", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Tenant", "Tenant")
                        .WithMany("Usuarios")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("API.Data.Entities.Albaran", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("API.Data.Entities.Factura", b =>
                {
                    b.Navigation("Albaranes");

                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Cliente", b =>
                {
                    b.Navigation("Albaranes");

                    b.Navigation("Facturas");

                    b.Navigation("Presupuestos");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Presupuesto", b =>
                {
                    b.Navigation("Albaranes");

                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Producto", b =>
                {
                    b.Navigation("LineasAlbaran");

                    b.Navigation("LineasFactura");

                    b.Navigation("LineasPresupuesto");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.SerieNumeracion", b =>
                {
                    b.Navigation("Albaranes");

                    b.Navigation("Facturas");

                    b.Navigation("Presupuestos");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Tenant", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Productos");

                    b.Navigation("Series");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
